### ISSUE TITLE
[install_github] GITHUB_PAT error for public R packages on GitLab Pages

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hadley/devtools#1676]
Hey,

I'm struggling to install R packages from Github inside a GitLab runner. 

This is my setup:
I'm trying to set up a GitLab Runner to display a gitbook generated using the **bookdown** package on a GitLab server.

Since GitLab doesn't work with a service like Travis but with Docker images, I created a Docker image containing both R-3.4.0 and loads of dependencies my package needs. Since I want to have the newest version of my package, I advice the script to install it using **devtools::install_github()**. My **.gitlab-ci.yml** looks like

```
image: thegreatwhiteshark/climex-r-ubuntu:1.0.0

pages:
  stage: deploy
  before_script:
    # - mkdir tmpBuild
    # - cd tmpBuild
    # - git clone https://github.com/theGreatWhiteShark/climex.git
    # - cd climex
    # - R -q -e 'devtools::install()'
    - R -q -e 'devtools::install_github("theGreatWhiteShark/climex" )'
  script:
    - R -q -e 'bookdown::render_book( "01-introduction.Rmd", "bookdown::gitbook()" )'
  artifacts:
    paths:
      - public
  only:
    - master
```

Now whenever the CI is running it already fails in the *before_script* part. The **install_github()** commands produces
```
> devtools::install_github( "theGreatWhiteShark/climex" )
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Downloading GitHub repo theGreatWhiteShark/climex@master
from URL https://api.github.com/repos/theGreatWhiteShark/climex/zipball/master
Installation failed: error in running command
```
The commented code unfortunately fails as well, since my package depends on two other R packages hosted on Github.

I'm using **devtools_1.13.4**

Reading [the github](https://bookdown.org/yihui/bookdown/github.html) section of the bookdown book I understand one needs the GITHUB_PAT to access private repositories or to provide write permission for a service, e.g. like Travis.

But **all packages** I want to install are **public**. The repository I install the packages into is private, but I don't see how this would affect the package installation. 

So, can you explain to me why a personal access token is required here? And if it is really necessary, how would the encryption of the token looks like? `travis encrypt` is a Github-only solution.

Cheers 

P.S. The docker image is using Ubuntu 16.04 and both the installation from the repositories of the system and the installation of R packages using **install.packages()** works within it.
